// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK
typedef void (*UniffiForeignFutureDroppedCallback)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_CLONE
typedef uint64_t (*UniffiCallbackInterfaceClone)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_DROPPED_CALLBACK_STRUCT
typedef struct UniffiForeignFutureDroppedCallbackStruct {
    uint64_t handle;
    UniffiForeignFutureDroppedCallback _Nonnull free;
} UniffiForeignFutureDroppedCallbackStruct;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U8
typedef struct UniffiForeignFutureResultU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureResultU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I8
typedef struct UniffiForeignFutureResultI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureResultI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U16
typedef struct UniffiForeignFutureResultU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureResultU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I16
typedef struct UniffiForeignFutureResultI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureResultI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U32
typedef struct UniffiForeignFutureResultU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureResultU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I32
typedef struct UniffiForeignFutureResultI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureResultI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_U64
typedef struct UniffiForeignFutureResultU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureResultU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_I64
typedef struct UniffiForeignFutureResultI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureResultI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F32
typedef struct UniffiForeignFutureResultF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureResultF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_F64
typedef struct UniffiForeignFutureResultF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureResultF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_RUST_BUFFER
typedef struct UniffiForeignFutureResultRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureResultRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureResultRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_RESULT_VOID
typedef struct UniffiForeignFutureResultVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureResultVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureResultVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD0
typedef void (*UniffiCallbackInterfaceSessionCallbackMethod0)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD1
typedef void (*UniffiCallbackInterfaceSessionCallbackMethod1)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD2
typedef void (*UniffiCallbackInterfaceSessionCallbackMethod2)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD3
typedef void (*UniffiCallbackInterfaceSessionCallbackMethod3)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD4
typedef void (*UniffiCallbackInterfaceSessionCallbackMethod4)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD5
typedef void (*UniffiCallbackInterfaceSessionCallbackMethod5)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD6
typedef void (*UniffiCallbackInterfaceSessionCallbackMethod6)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD7
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD7
typedef void (*UniffiCallbackInterfaceSessionCallbackMethod7)(uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD8
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD8
typedef void (*UniffiCallbackInterfaceSessionCallbackMethod8)(uint64_t, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD9
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_SESSION_CALLBACK_METHOD9
typedef void (*UniffiCallbackInterfaceSessionCallbackMethod9)(uint64_t, RustBuffer, void* _Nonnull, 
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_SESSION_CALLBACK
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_SESSION_CALLBACK
typedef struct UniffiVTableCallbackInterfaceSessionCallback {
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
    UniffiCallbackInterfaceClone _Nonnull uniffiClone;
    UniffiCallbackInterfaceSessionCallbackMethod0 _Nonnull onRoomStateChanged;
    UniffiCallbackInterfaceSessionCallbackMethod1 _Nonnull onTrackChanged;
    UniffiCallbackInterfaceSessionCallbackMethod2 _Nonnull onPlaybackChanged;
    UniffiCallbackInterfaceSessionCallbackMethod3 _Nonnull onParticipantJoined;
    UniffiCallbackInterfaceSessionCallbackMethod4 _Nonnull onParticipantLeft;
    UniffiCallbackInterfaceSessionCallbackMethod5 _Nonnull onRoomEnded;
    UniffiCallbackInterfaceSessionCallbackMethod6 _Nonnull onError;
    UniffiCallbackInterfaceSessionCallbackMethod7 _Nonnull onConnected;
    UniffiCallbackInterfaceSessionCallbackMethod8 _Nonnull onDisconnected;
    UniffiCallbackInterfaceSessionCallbackMethod9 _Nonnull onSyncStatus;
} UniffiVTableCallbackInterfaceSessionCallback;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_CLONE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_CLONE_SESSION
uint64_t uniffi_cider_core_fn_clone_session(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_FREE_SESSION
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_FREE_SESSION
void uniffi_cider_core_fn_free_session(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_CONSTRUCTOR_SESSION_NEW
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_CONSTRUCTOR_SESSION_NEW
uint64_t uniffi_cider_core_fn_constructor_session_new(RustCallStatus *_Nonnull out_status
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_BROADCAST_PLAYBACK
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_BROADCAST_PLAYBACK
void uniffi_cider_core_fn_method_session_broadcast_playback(uint64_t ptr, RustBuffer track, int8_t is_playing, uint64_t position_ms, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_BROADCAST_TRACK_CHANGE
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_BROADCAST_TRACK_CHANGE
void uniffi_cider_core_fn_method_session_broadcast_track_change(uint64_t ptr, RustBuffer track, uint64_t position_ms, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_CHECK_CIDER_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_CHECK_CIDER_CONNECTION
void uniffi_cider_core_fn_method_session_check_cider_connection(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_CREATE_ROOM
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_CREATE_ROOM
RustBuffer uniffi_cider_core_fn_method_session_create_room(uint64_t ptr, RustBuffer display_name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_GET_IS_PLAYING
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_GET_IS_PLAYING
int8_t uniffi_cider_core_fn_method_session_get_is_playing(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_GET_NOW_PLAYING
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_GET_NOW_PLAYING
RustBuffer uniffi_cider_core_fn_method_session_get_now_playing(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_GET_PLAYBACK_STATE
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_GET_PLAYBACK_STATE
RustBuffer uniffi_cider_core_fn_method_session_get_playback_state(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_GET_ROOM_STATE
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_GET_ROOM_STATE
RustBuffer uniffi_cider_core_fn_method_session_get_room_state(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_IS_HOST
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_IS_HOST
int8_t uniffi_cider_core_fn_method_session_is_host(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_IS_IN_ROOM
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_IS_IN_ROOM
int8_t uniffi_cider_core_fn_method_session_is_in_room(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_JOIN_ROOM
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_JOIN_ROOM
void uniffi_cider_core_fn_method_session_join_room(uint64_t ptr, RustBuffer room_code, RustBuffer display_name, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_LEAVE_ROOM
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_LEAVE_ROOM
void uniffi_cider_core_fn_method_session_leave_room(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_SET_CALLBACK
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_SET_CALLBACK
void uniffi_cider_core_fn_method_session_set_callback(uint64_t ptr, uint64_t callback, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_SET_CIDER_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_SET_CIDER_TOKEN
void uniffi_cider_core_fn_method_session_set_cider_token(uint64_t ptr, RustBuffer token, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_SYNC_NEXT
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_SYNC_NEXT
void uniffi_cider_core_fn_method_session_sync_next(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_SYNC_PAUSE
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_SYNC_PAUSE
void uniffi_cider_core_fn_method_session_sync_pause(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_SYNC_PLAY
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_SYNC_PLAY
void uniffi_cider_core_fn_method_session_sync_play(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_SYNC_PREVIOUS
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_SYNC_PREVIOUS
void uniffi_cider_core_fn_method_session_sync_previous(uint64_t ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_SYNC_SEEK
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_SYNC_SEEK
void uniffi_cider_core_fn_method_session_sync_seek(uint64_t ptr, uint64_t position_ms, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_TRANSFER_HOST
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_METHOD_SESSION_TRANSFER_HOST
void uniffi_cider_core_fn_method_session_transfer_host(uint64_t ptr, RustBuffer peer_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_INIT_CALLBACK_VTABLE_SESSIONCALLBACK
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_FN_INIT_CALLBACK_VTABLE_SESSIONCALLBACK
void uniffi_cider_core_fn_init_callback_vtable_sessioncallback(const UniffiVTableCallbackInterfaceSessionCallback* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUSTBUFFER_ALLOC
RustBuffer ffi_cider_core_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_cider_core_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUSTBUFFER_FREE
void ffi_cider_core_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUSTBUFFER_RESERVE
RustBuffer ffi_cider_core_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_U8
void ffi_cider_core_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_U8
void ffi_cider_core_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_U8
void ffi_cider_core_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_cider_core_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_I8
void ffi_cider_core_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_I8
void ffi_cider_core_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_I8
void ffi_cider_core_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_I8
int8_t ffi_cider_core_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_U16
void ffi_cider_core_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_U16
void ffi_cider_core_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_U16
void ffi_cider_core_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_cider_core_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_I16
void ffi_cider_core_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_I16
void ffi_cider_core_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_I16
void ffi_cider_core_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_I16
int16_t ffi_cider_core_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_U32
void ffi_cider_core_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_U32
void ffi_cider_core_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_U32
void ffi_cider_core_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_cider_core_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_I32
void ffi_cider_core_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_I32
void ffi_cider_core_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_I32
void ffi_cider_core_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_I32
int32_t ffi_cider_core_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_U64
void ffi_cider_core_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_U64
void ffi_cider_core_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_U64
void ffi_cider_core_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_cider_core_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_I64
void ffi_cider_core_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_I64
void ffi_cider_core_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_I64
void ffi_cider_core_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_I64
int64_t ffi_cider_core_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_F32
void ffi_cider_core_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_F32
void ffi_cider_core_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_F32
void ffi_cider_core_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_F32
float ffi_cider_core_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_F64
void ffi_cider_core_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_F64
void ffi_cider_core_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_F64
void ffi_cider_core_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_F64
double ffi_cider_core_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_cider_core_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_cider_core_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_cider_core_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_cider_core_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_POLL_VOID
void ffi_cider_core_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_CANCEL_VOID
void ffi_cider_core_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_FREE_VOID
void ffi_cider_core_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_RUST_FUTURE_COMPLETE_VOID
void ffi_cider_core_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_BROADCAST_PLAYBACK
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_BROADCAST_PLAYBACK
uint16_t uniffi_cider_core_checksum_method_session_broadcast_playback(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_BROADCAST_TRACK_CHANGE
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_BROADCAST_TRACK_CHANGE
uint16_t uniffi_cider_core_checksum_method_session_broadcast_track_change(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_CHECK_CIDER_CONNECTION
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_CHECK_CIDER_CONNECTION
uint16_t uniffi_cider_core_checksum_method_session_check_cider_connection(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_CREATE_ROOM
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_CREATE_ROOM
uint16_t uniffi_cider_core_checksum_method_session_create_room(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_GET_IS_PLAYING
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_GET_IS_PLAYING
uint16_t uniffi_cider_core_checksum_method_session_get_is_playing(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_GET_NOW_PLAYING
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_GET_NOW_PLAYING
uint16_t uniffi_cider_core_checksum_method_session_get_now_playing(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_GET_PLAYBACK_STATE
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_GET_PLAYBACK_STATE
uint16_t uniffi_cider_core_checksum_method_session_get_playback_state(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_GET_ROOM_STATE
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_GET_ROOM_STATE
uint16_t uniffi_cider_core_checksum_method_session_get_room_state(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_IS_HOST
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_IS_HOST
uint16_t uniffi_cider_core_checksum_method_session_is_host(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_IS_IN_ROOM
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_IS_IN_ROOM
uint16_t uniffi_cider_core_checksum_method_session_is_in_room(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_JOIN_ROOM
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_JOIN_ROOM
uint16_t uniffi_cider_core_checksum_method_session_join_room(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_LEAVE_ROOM
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_LEAVE_ROOM
uint16_t uniffi_cider_core_checksum_method_session_leave_room(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_SET_CALLBACK
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_SET_CALLBACK
uint16_t uniffi_cider_core_checksum_method_session_set_callback(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_SET_CIDER_TOKEN
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_SET_CIDER_TOKEN
uint16_t uniffi_cider_core_checksum_method_session_set_cider_token(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_SYNC_NEXT
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_SYNC_NEXT
uint16_t uniffi_cider_core_checksum_method_session_sync_next(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_SYNC_PAUSE
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_SYNC_PAUSE
uint16_t uniffi_cider_core_checksum_method_session_sync_pause(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_SYNC_PLAY
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_SYNC_PLAY
uint16_t uniffi_cider_core_checksum_method_session_sync_play(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_SYNC_PREVIOUS
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_SYNC_PREVIOUS
uint16_t uniffi_cider_core_checksum_method_session_sync_previous(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_SYNC_SEEK
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_SYNC_SEEK
uint16_t uniffi_cider_core_checksum_method_session_sync_seek(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_TRANSFER_HOST
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSION_TRANSFER_HOST
uint16_t uniffi_cider_core_checksum_method_session_transfer_host(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_CONSTRUCTOR_SESSION_NEW
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_CONSTRUCTOR_SESSION_NEW
uint16_t uniffi_cider_core_checksum_constructor_session_new(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_ROOM_STATE_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_ROOM_STATE_CHANGED
uint16_t uniffi_cider_core_checksum_method_sessioncallback_on_room_state_changed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_TRACK_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_TRACK_CHANGED
uint16_t uniffi_cider_core_checksum_method_sessioncallback_on_track_changed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_PLAYBACK_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_PLAYBACK_CHANGED
uint16_t uniffi_cider_core_checksum_method_sessioncallback_on_playback_changed(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_PARTICIPANT_JOINED
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_PARTICIPANT_JOINED
uint16_t uniffi_cider_core_checksum_method_sessioncallback_on_participant_joined(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_PARTICIPANT_LEFT
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_PARTICIPANT_LEFT
uint16_t uniffi_cider_core_checksum_method_sessioncallback_on_participant_left(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_ROOM_ENDED
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_ROOM_ENDED
uint16_t uniffi_cider_core_checksum_method_sessioncallback_on_room_ended(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_ERROR
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_ERROR
uint16_t uniffi_cider_core_checksum_method_sessioncallback_on_error(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_CONNECTED
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_CONNECTED
uint16_t uniffi_cider_core_checksum_method_sessioncallback_on_connected(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_DISCONNECTED
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_DISCONNECTED
uint16_t uniffi_cider_core_checksum_method_sessioncallback_on_disconnected(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_SYNC_STATUS
#define UNIFFI_FFIDEF_UNIFFI_CIDER_CORE_CHECKSUM_METHOD_SESSIONCALLBACK_ON_SYNC_STATUS
uint16_t uniffi_cider_core_checksum_method_sessioncallback_on_sync_status(void
    
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_CIDER_CORE_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_CIDER_CORE_UNIFFI_CONTRACT_VERSION
uint32_t ffi_cider_core_uniffi_contract_version(void
    
);
#endif

